kind: pipeline
type: docker
name: uozi-debian-base-slim

steps:
    - name: build and push to aliyun
      image: plugins/docker
      settings:
          repo: registry.cn-shenzhen.aliyuncs.com/uozi/debian-base-slim
          registry: registry.cn-shenzhen.aliyuncs.com
          tags: latest
          dockerfile: uozi-debian-base-slim/Dockerfile
          context: .
          username:
              from_secret: aliyun_registry_username
          password:
              from_secret: aliyun_registry_password
          platform:
            - linux/amd64
            - linux/arm/v5
            - linux/arm/v6
            - linux/arm/v7
            - linux/arm64
  
    - name: build and push to dockerhub
      image: plugins/docker
      settings:
          repo: uozi/uozi-debian-base-slim
          tags: latest
          dockerfile: uozi-debian-base-slim/Dockerfile
          context: .
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          platform:
            - linux/amd64
            - linux/arm/v5
            - linux/arm/v6
            - linux/arm/v7
            - linux/arm64
    
    - name: notify
      image: uozi/drone-bark
      depends_on:
        - build and push to aliyun
        - build and push to dockerhub
      settings:
        server_url: https://push.jackyu.cn/
        bark_device:
            from_secret: bark_device
        icon: https://dl.jackyu.cn/icon/drone.png
        bark_group: Drone CI
        bark_level: timeSensitive
      when:
        status: [ success, failure ]

---
kind: pipeline
type: docker
name: nginx-ui-base

steps:
    - name: build and push to aliyun
      image: plugins/docker
      settings:
          repo: registry.cn-shenzhen.aliyuncs.com/uozi/nginx-ui-base
          registry: registry.cn-shenzhen.aliyuncs.com
          tags: latest
          dockerfile: nginx-ui-base/Dockerfile
          context: .
          username:
              from_secret: aliyun_registry_username
          password:
              from_secret: aliyun_registry_password
          platform:
            - linux/amd64
            - linux/arm/v5
            - linux/arm/v6
            - linux/arm/v7
            - linux/arm64
  
    - name: build and push to dockerhub
      image: plugins/docker
      settings:
          repo: uozi/nginx-ui-base
          tags: latest
          dockerfile: nginx-ui-base/Dockerfile
          context: .
          username:
              from_secret: docker_username
          password:
              from_secret: docker_password
          platform:
            - linux/amd64
            - linux/arm/v5
            - linux/arm/v6
            - linux/arm/v7
            - linux/arm64

    - name: notify
      image: uozi/drone-bark
      depends_on:
        - build and push to aliyun
        - build and push to dockerhub
      settings:
        server_url: https://push.jackyu.cn/
        bark_device:
            from_secret: bark_device
        icon: https://dl.jackyu.cn/icon/drone.png
        bark_group: Drone CI
        bark_level: timeSensitive
      when:
        status: [ success, failure ]


volumes:
- name: dockersock
  host:
    path: /var/run