name: Build and Push Docker Images

on:
    schedule:
      - cron: '0 0 * * *' # 00:00 AM UTC
    push:
      branches:
        - main

jobs:
  uozi-debian-base-slim:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Debian Base to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: .
        file: uozi-debian-base-slim/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: uozi/uozi-debian-base-slim:latest
        platforms: linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64

  nginx-ui-base:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Debian Base to DockerHub
      uses: docker/build-push-action@v4
      with:
        context: .
        file: nginx-ui-base/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: uozi/nginx-ui-base:latest
        platforms: linux/amd64,linux/arm/v5,linux/arm/v6,linux/arm/v7,linux/arm64
