name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
          image: [ uozi-debian-base-slim, nginx-ui-base ]
          
    env:
      image: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v3
      name: Build the Docker image
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./${{ env.image }}
        file: ./${{ env.image }}/Dockerfile
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6,linux/arm/v5
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
            ${{ secrets.DOCKERHUB_USER }}/${{ env.image }}:latest

